services:
  - type: web
    name: bevyfinder-api
    env: node
    plan: free
    buildCommand: cd server && npm install --production
    startCommand: cd server && npm start
    healthCheckPath: /health
