services:
  - type: web
    name: bevyfinder-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server-minimal.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d 